module.exports = [{
        "url": "emoji_01.png",
        "alt": "[开心]"
    }, {
        "url": "emoji_02.png",
        "alt": "[高兴]"
    }, {
        "url": "emoji_03.png",
        "alt": "[哈哈]"
    }, {
        "url": "emoji_04.png",
        "alt": "[灿烂]"
    }, {
        "url": "emoji_05.png",
        "alt": "[大笑]"
    }, {
        "url": "emoji_06.png",
        "alt": "[汗臭]"
    }, {
        "url": "emoji_07.png",
        "alt": "[地板上笑]"
    }, {
        "url": "emoji_08.png",
        "alt": "[笑哭]"
    }, {
        "url": "emoji_09.png",
        "alt": "[微笑]"
    }, {
        "url": "emoji_10.png",
        "alt": "[颠倒]"
    }, {
        "url": "emoji_11.png",
        "alt": "[眨眼]"
    }, {
        "url": "emoji_12.png",
        "alt": "[面带笑容]"
    }, {
        "url": "emoji_13.png",
        "alt": "[晕笑]"
    }, {
        "url": "emoji_14.png",
        "alt": "[爱心笑]"
    }, {
        "url": "emoji_15.png",
        "alt": "[喜欢]"
    }, {
        "url": "emoji_16.png",
        "alt": "[开眼界]"
    }, {
        "url": "emoji_17.png",
        "alt": "[飞吻]"
    }, {
        "url": "emoji_18.png",
        "alt": "[亲亲]"
    }, {
        "url": "emoji_19.png",
        "alt": "[面带微笑]"
    }, {
        "url": "emoji_20.png",
        "alt": "[闭眼亲亲]"
    }, {
        "url": "emoji_21.png",
        "alt": "[笑脸亲亲]"
    }, {
        "url": "emoji_22.png",
        "alt": "[面对食物]"
    }, {
        "url": "emoji_23.png",
        "alt": "[吐舌]"
    }, {
        "url": "emoji_24.png",
        "alt": "[眨眼吐舌]"
    },
    {
        "url": "emoji_25.png",
        "alt": "[赞尼]"
    }, {
        "url": "emoji_26.png",
        "alt": "[鬼脸]"
    }, {
        "url": "emoji_27.png",
        "alt": "[钱嘴]"
    }, {
        "url": "emoji_28.png",
        "alt": "[拥抱]"
    }, {
        "url": "emoji_29.png",
        "alt": "[偷笑]"
    }, {
        "url": "emoji_30.png",
        "alt": "[嘘]"
    }, {
        "url": "emoji_31.png",
        "alt": "[思考]"
    }, {
        "url": "emoji_32.png",
        "alt": "[闭嘴]"
    }, {
        "url": "emoji_33.png",
        "alt": "[翘眉毛]"
    }, {
        "url": "emoji_34.png",
        "alt": "[中性]"
    }, {
        "url": "emoji_35.png",
        "alt": "[无表情]"
    }, {
        "url": "emoji_36.png",
        "alt": "[无嘴脸]"
    }, {
        "url": "emoji_37.png",
        "alt": "[傻笑]"
    }, {
        "url": "emoji_38.png",
        "alt": "[无趣]"
    }, {
        "url": "emoji_39.png",
        "alt": "[白眼]"
    }, {
        "url": "emoji_40.png",
        "alt": "[尴尬]"
    }, {
        "url": "emoji_41.png",
        "alt": "[说谎]"
    }, {
        "url": "emoji_42.png",
        "alt": "[舒缓]"
    }, {
        "url": "emoji_43.png",
        "alt": "[沉思]"
    }, {
        "url": "emoji_44.png",
        "alt": "[沉睡]"
    }, {
        "url": "emoji_45.png",
        "alt": "[流口水]"
    }, {
        "url": "emoji_46.png",
        "alt": "[睡觉]"
    }, {
        "url": "emoji_47.png",
        "alt": "[感冒]"
    }, {
        "url": "emoji_48.png",
        "alt": "[发热]"
    },
    {
        "url": "emoji_49.png",
        "alt": "[受伤]"
    }, {
        "url": "emoji_50.png",
        "alt": "[恶心]"
    }, {
        "url": "emoji_51.png",
        "alt": "[呕吐]"
    }, {
        "url": "emoji_52.png",
        "alt": "[打喷嚏]"
    }, {
        "url": "emoji_53.png",
        "alt": "[炎热]"
    }, {
        "url": "emoji_54.png",
        "alt": "[寒冷]"
    }, {
        "url": "emoji_55.png",
        "alt": "[毛茸茸]"
    }, {
        "url": "emoji_56.png",
        "alt": "[头晕]"
    }, {
        "url": "emoji_57.png",
        "alt": "[爆炸头]"
    }, {
        "url": "emoji_58.png",
        "alt": "[牛仔帽]"
    }, {
        "url": "emoji_59.png",
        "alt": "[聚会]"
    }, {
        "url": "emoji_60.png",
        "alt": "[酷]"
    }, {
        "url": "emoji_61.png",
        "alt": "[书呆子]"
    }, {
        "url": "emoji_62.png",
        "alt": "[观察]"
    }, {
        "url": "emoji_63.png",
        "alt": "[困惑]"
    }, {
        "url": "emoji_64.png",
        "alt": "[担心]"
    }, {
        "url": "emoji_65.png",
        "alt": "[皱眉]"
    }, {
        "url": "emoji_66.png",
        "alt": "[不开心]"
    }, {
        "url": "emoji_67.png",
        "alt": "[张嘴]"
    }, {
        "url": "emoji_68.png",
        "alt": "[寂静]"
    }, {
        "url": "emoji_69.png",
        "alt": "[惊讶]"
    }, {
        "url": "emoji_70.png",
        "alt": "[害羞]"
    }, {
        "url": "emoji_71.png",
        "alt": "[恳求]"
    }, {
        "url": "emoji_72.png",
        "alt": "[丧气]"
    },
    {
        "url": "emoji_73.png",
        "alt": "[痛苦]"
    }, {
        "url": "emoji_74.png",
        "alt": "[可怕]"
    }, {
        "url": "emoji_75.png",
        "alt": "[焦虑]"
    }, {
        "url": "emoji_76.png",
        "alt": "[悲伤]"
    }, {
        "url": "emoji_77.png",
        "alt": "[哭泣]"
    }, {
        "url": "emoji_78.png",
        "alt": "[聚会]"
    }, {
        "url": "emoji_79.png",
        "alt": "[恐惧]"
    }, {
        "url": "emoji_80.png",
        "alt": "[极度困惑]"
    }, {
        "url": "emoji_81.png",
        "alt": "[执着]"
    }, {
        "url": "emoji_82.png",
        "alt": "[失望]"
    }, {
        "url": "emoji_83.png",
        "alt": "[垂头丧气]"
    }, {
        "url": "emoji_84.png",
        "alt": "[疲倦]"
    }, {
        "url": "emoji_85.png",
        "alt": "[十分疲倦]"
    }, {
        "url": "emoji_86.png",
        "alt": "[打哈欠]"
    }, {
        "url": "emoji_87.png",
        "alt": "[出气]"
    }, {
        "url": "emoji_88.png",
        "alt": "[愤怒]"
    }, {
        "url": "emoji_89.png",
        "alt": "[生气]"
    }, {
        "url": "emoji_90.png",
        "alt": "[咒骂]"
    }

]